datavault_extension:
  outputs:
    dev:
      type: duckdb
      path: "target/WILLIBALD_DATA_VAULT_WITH_DBT.duckdb"
      extensions:
        - httpfs
        - parquet
      schema: <schema>
  target: dev